//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TG.rc
//
#define IDS_TG                          1
#define IDS_TG_PPG                      2
#define IDCANCEL2                       4
#define IDI_ABOUTDLL                    5
#define IDB_TG                          6
#define IDD_ABOUTBOX_TG                 7
#define ID_11_11                        90
#define IDC_POINTER                     104
#define IDC_POINTER_COPY                105
#define IDR_RBUTTON_POPMENU             131
#define IDD_DLG_WAIT                    135
#define IDS_TG_PPG_CAPTION              200
#define IDD_PROPPAGE_TG                 200
#define IDC_SPLIT_TRAINID1              201
#define IDC_SPLIT_TRAINID2              202
#define IDD_DLG_PROHIBIT_MEET           203
#define IDC_BUTTON3                     203
#define IDC_COMBO_LOCOL_TYPE            204
#define IDC_STATIC_TEXT                 205
#define IDD_DIALOG_NOTE_TEXT            205
#define IDD_DLG_TG_COLOR                206
#define IDC_RADIO_IMPORT                207
#define IDC_RADIO_BAO                   208
#define IDC_RADIO_NO                    209
#define IDC_RADIO_RED_RECT              210
#define IDC_RADIO_BLUE_RECT             211
#define IDC_RADIO_RED_ROUND             212
#define IDC_RADIO_BLUE_ROUND            213
#define IDC_EDIT_TEXT                   214
#define IDC_EDIT_DCMDNO                 215
#define IDC_RADIO_RED_WORD              215
#define IDC_STATIC_ABS_INHIBIT          216
#define IDC_RADIO_BLUE_ROUND2           216
#define IDC_RADIO_BLUE_WORD             216
#define IDC_DATETIMEPICKER1             217
#define IDC_TRAIN_INDEX                 218
#define IDC_BTN_FIND                    219
#define IDC_CHECK_DELETE                220
#define IDC_DATETIMEPICKER5             221
#define IDC_DATETIMEPICKER6             222
#define IDC_DATETIMEPICKER7             223
#define IDC_COMBO_CZH                   223
#define IDC_DATETIMEPICKER8             224
#define IDC_DATETIMEPICKER9             225
#define IDD_DLG_MODIFY_TRAIN_INOUT_INDEX 226
#define IDD_DLG_ABS_STOP                227
#define IDD_DLG_COPY_TRAIN              228
#define IDC_STATIC_TIG                  228
#define IDD_DLG_SHUAI_MANAGER           229
#define IDD_DLG_CHANGE_WHOLE_SIDE       230
#define IDD_ABS_LANZHOU_FIX_PROPERTY    231
#define IDC_PROGRESS1                   232
#define IDD_DLG_SEL_MUTI_MARK           233
#define IDD_DLG_CZH                     234
#define IDD_DLG_CZH_SHOW                235
#define IDD_DLG_INPUT                   236
#define IDD_DLG_GEN_RETURNID            237
#define IDD_DIALOG_MSG                  238
#define IDC_LIST4                       239
#define IDC_DATETIMEPICKER2             240
#define IDC_DATETIMEPICKER3             241
#define IDC_DATETIMEPICKER4             242
#define IDC_CURSOR1                     243
#define IDC_RECEIVE_CURSOR              244
#define IDD_DLG_FIND_TRAIN_RESULT       244
#define IDC_SGTIME_ET                   245
#define IDD_DLG_JIAOLU_EIDT             245
#define IDC_SGDATE_ST                   246
#define IDD_DLG_INPUT_RETURN_ID         246
#define IDC_SGDATE_ET                   247
#define IDD_DLG_RETURN_ID_SEL           247
#define IDC_SGTIME_ST                   248
#define IDD_DLG_JIAOLU_VIEW             248
#define IDD_DLG_MARK_TIMESPAN           249
#define IDD_DLG_JIAOLU_SELECT_TRAIN     250
#define IDC_LIST_RESULT                 251
#define IDC_BNT_CLOSE                   252
#define IDC_STATIC_ABS_TIME             253
#define IDC_SEL_ALL                     254
#define IDC_SEL_NONE                    255
#define IDC_EDIT_MOVE_MINUTE            256
#define IDC_LIST                        260
#define IDC_MODIFY_CHK_ALL              262
#define ID_CHANGE_TRACKS_BEGIN          263
#define IDD_DIALOG_WITH_PASSWORD        264
#define ID_CHANGE_TRACKS_END            530
#define IDD_DLG_CHANGE_TID              545
#define ID_GEN_DCMD                     550
#define ID_STAY_TO_PASS                 601
#define ID_ADDTRAIN_CANCEL              602
#define ID_SIDE_TIANCHUANG_G            605
#define ID_ROUTE_AUTO_MARK              606
#define ID_FENJIEKOU_TIME               607
#define ID_IN_STATION_RETURN            608
#define ID_OUT_STATION_RETURN           609
#define ID_NOT_STATION_RETURN           610
#define ID_NOT_START_RETURN             611
#define ID_DEPART_BY_MEET               616
#define ID_DEPART_BY_PLAN               617
#define IDD_ABS_INHIBIT_PROPERTY        718
#define IDD_ABS_SLOW_PROPERTY           719
#define IDD_ABS_SELF_CLOSE_PROPERTY     720
#define IDD_ABS_FIX_PROPERTY            721
#define IDD_STATION_SLOW_PROPERTY       722
#define IDD_STATION_INHIBIT_PROPERTY    723
#define IDD_FIND_TRAIN                  724
#define IDD_DLG_MANUAL_REPORT           725
#define IDD_DLG_CHANGE_TRACK            744
#define IDD_DLG_TRANSPORT_INFO          746
#define IDD_DLG_PLAN_PARA               747
#define IDD_PGE_TRAIN_ATT2              752
#define IDD_PGE_TRAIN_ATT1              753
#define IDD_DIG_GOON_RETURN             791
#define IDD_TRAIN_DATA_DLG              793
#define IDD_SUPER_PASS                  798
#define IDD_STATION_INHIBIT_PROPERTY_LARGE 799
#define IDD_STATION_SLOW_PROPERTY_LARGE 800
#define IDD_STATION_SLOW_PROPERTY_MIDDLE 801
#define IDD_STATION_INHIBIT_PROPERTY_MIDDLE 802
#define IDD_DLG_GUAJICHE                804
#define IDD_ABS_ELE_FIX_G               812
#define IDD_DLG_MULTISEL_OPERATE        820
#define IDD_ABS_SLOW_PROPERTYEX         821
#define IDD_DLG_CHANGE_HATTID           838
#define IDD_DLG_DRAW_ENDWAY_SELECT      852
#define IDD_DLG_MESSAGEBOX              858
#define IDD_DLG_ROUTE_AUTO_FLAG         867
#define IDD_SPLIT_TRAIN                 894
#define IDD_COMBINE_TRAIN               895
#define IDD_DLG_ROUTE_MODE              902
#define IDD_DLG_SET_MULTI_TRAIN_SIDE_LOCK 948
#define IDD_DLG_QUICK_MODIFY_MULTI_TRAINS 953
#define IDC_CANCEL                      1011
#define IDC_CHANGE_STATIC               1013
#define IDC_CHANGE_STATIC1              1014
#define IDC_CHANGE_OLDID                1015
#define IDC_CHANGE_NEWID                1016
#define IDC_CHANGE_ACK                  1018
#define IDC_WAIT_STR                    1018
#define IDC_CHANGE_CANCEL               1019
#define IDC_CHANGE_CANCEL_ACK           1020
#define IDC_ATTRIBUTE_RUNTYPE           1209
#define IDC_ATTRIBUTE_TRAINID           1211
#define IDC_ATTRIBUTE_STATIC2           1212
#define IDC_ATTRIBUTE_TRAINTYPE         1213
#define IDC_ATTRIBUTE_STATIC3           1214
#define IDC_ATTRIBUTE_RUNCLASS          1214
#define IDC_ATTRIBUTE_STATIC4           1215
#define IDC_ATTRIBUTE_ABS               1215
#define IDC_ATTRIBUTE_LENGTH            1216
#define IDC_ATTRIBUTE_STATIC5           1217
#define IDC_ATTRIBUTE_OVER_LEVEL        1218
#define IDC_ATTRIBUTE_STATIC7           1219
#define IDC_ATTRIBUTE_OVER_LIMIT        1220
#define IDC_ATTRIBUTE_NO_MEET           1221
#define IDC_ATTRIBUTE_ENGINE            1222
#define IDC_ATTRIBUTE_CANCEL            1224
#define IDC_COMBO_STATION               1489
#define IDC_START_STATION               1551
#define IDC_END_STATION                 1552
#define IDC_START_TIME                  1553
#define IDC_END_TIME                    1554
#define IDC_TRAIN_LIST                  1571
#define IDC_COMBO4                      1572
#define IDC_LIST1                       1593
#define IDC_STATION                     1593
#define IDC_LIST2                       1594
#define IDC_EDIT1                       1595
#define IDC_COMBO1                      1596
#define IDC_EDIT_TICKET                 1596
#define IDC_EDIT_CZH                    1596
#define IDC_COMBO5                      1597
#define IDC_EDIT3                       1598
#define IDC_EDIT4                       1599
#define IDC_EDIT8                       1601
#define IDC_EDIT6                       1602
#define IDC_EDIT11                      1603
#define IDC_EDIT12                      1604
#define IDC_EDIT2                       1613
#define IDC_RADIO1                      1613
#define IDC_RADIO_SHIGU                 1613
#define IDC_RADIO_SLOW                  1613
#define IDC_TRAIN_ID                    1614
#define IDC_RADIO2                      1614
#define IDC_EDIT_LENGTH                 1614
#define IDC_RADIO_NOTE                  1614
#define IDC_EDIT7                       1614
#define IDC_RADIO_MOVE                  1614
#define IDC_EDIT5                       1615
#define IDC_EDIT_WEIGHT                 1615
#define IDC_EDIT_BEHIND_NO              1616
#define IDC_EDIT10                      1617
#define IDC_EDIT1_TRAIN_NUM             1617
#define IDC_EDIT1_F_STATION             1618
#define IDC_EDIT1_E_STATION             1619
#define IDC_EDIT_F_PLAN_TIME            1620
#define IDC_EDIT1_E_PLAN_TIME           1621
#define IDC_EDIT_E_A_TIME               1622
#define IDC_EDIT_F_A_TIME               1623
#define IDC_LINEUP_WORKCONTENT          1716
#define IDC_LINEUP_SIDE                 1717
#define IDC_LINEUP_LIST                 1718
#define IDC_LINEUP_TRAINID              1719
#define IDC_LINEUP_STATION              1720
#define IDC_LINEUP_WORKTYPE             1721
#define IDC_LINEUP_INSERT               1722
#define IDC_LINEUP_CHANGE               1723
#define IDC_LINEUP_DELETE               1724
#define IDC_LINEUP_ACK                  1725
#define IDC_LINEUP_CANCEL               1726
#define IDC_TRAIN_PRIORITY_LIST         1727
#define IDC_TP_TOPMOST                  1728
#define IDC_TP_LOWMOST                  1729
#define IDC_TP_UP                       1730
#define IDC_TP_DOWN                     1731
#define IDC_TP_DEFAULT                  1732
#define IDC_TP_ACK                      1733
#define IDC_TP_CANCEL                   1734
#define IDC_MRP_UPDIR                   1746
#define IDC_MRP_DOWNDIR                 1747
#define IDC_MRP_ALLDIR                  1748
#define IDC_MRP_TRAINLIST               1749
#define IDC_MRP_ACK                     1750
#define IDC_MRP_CANCEL                  1751
#define IDC_MRP_PLAN_ARRIVE             1752
#define IDC_MRP_PLAN_DEPART             1753
#define IDC_MRP_ACTUAL_ARRIVE           1754
#define IDC_MRP_ACTUAL_DEPART           1755
#define IDC_MRP_STATIONLIST             1756
#define IDC_SBT_KECHE                   1757
#define IDC_SBT_FREIGHT                 1758
#define IDC_SBT_RECEIVE                 1759
#define IDC_SBT_START                   1760
#define IDC_SBT_ENDTIME                 1761
#define IDC_SBT_TRAINLIST               1762
#define IDC_SBT_STATIONLIST             1763
#define IDC_SBT_UPDIR                   1764
#define IDC_SBT_DOWNDIR                 1765
#define IDC_SBT_ALLDIR                  1766
#define IDC_SBT_STARTTIME               1767
#define IDC_SBT_DELETE                  1768
#define IDC_SBT_ACK                     1769
#define IDC_SBT_CANCEL                  1770
#define IDC_SLIDER1                     1771
#define IDC_SBT_GET                     1771
#define IDC_PPT_TRAIN_INSERT            1971
#define IDC_PPT_TRAIN_DELETE            1972
#define IDC_PPT_START_DATE              1990
#define IDC_PPT_START_TIME              1991
#define IDC_PPT_TIME_INTERVAL           1992
#define IDC_PPT_TRAINID                 1993
#define IDC_PPT_SELECT                  1994
#define IDC_PPT_TRAIN_PLAN              1995
#define IDC_PPT_BOXNUM                  1996
#define IDC_PPT_WEIGHT                  1997
#define IDC_PPT_LENGTH                  1998
#define IDC_PPT_PLAN_ACTUAL_SWITCH      1999
#define IDC_PPT_PASSTHROUGH             2001
#define IDC_PPT_TRAINREPORT             2002
#define IDC_PPT_SIMPLE_LIST             2003
#define IDC_PPT_COMBINE                 2004
#define IDC_PPT_TRAINREPORT_DELETE      2006
#define IDC_PPT_PROMPT                  2007
#define IDC_PPT_COMMIT                  2008
#define IDC_PPT_ROLLBACK                2009
#define IDC_PPT_SAVE                    2010
#define IDC_PPT_CANCEL                  2011
#define IDD_DIALOG_SEL_TRAIN            2012
#define IDC_BUTTON1                     2092
#define IDC_BUTTON2                     2093
#define IDC_BUTTON5                     2094
#define IDC_BUTTON6                     2095
#define IDC_BUTTON7                     2096
#define IDC_STATIC1                     2104
#define IDC_STATIC2                     2105
#define IDC_COMBO_TRACK                 2110
#define IDC_COMBO_TRACK2                2111
#define IDC_COMBO_NEXTABS               2111
#define IDC_COMBO_PREVIOUSABS           2112
#define IDC_EDIT_STATION                2112
#define IDC_EDIT_ABS                    2113
#define IDC_EDIT_ABS2                   2114
#define IDC_EDIT_WARNING                2115
#define IDC_ADJUST_START                2116
#define IDC_STOP_TIME                   2118
#define IDC_CHECK_ABS_TIME              2121
#define IDC_CHECK_TRACK                 2122
#define IDC_PASS_SIDE                   2123
#define IDC_NO_STOP_TRAIN               2124
#define IDC_CHECK_ABS_TIME2             2125
#define IDC_STOP_TIME_MIN               2126
#define IDC_BUTTON_DEL                  2131
#define IDC_TEXT                        2133
#define IDC_RADIO_TEXT                  2134
#define IDC_RADIO_ACCIDENT              2135
#define IDC_RADIO_IMPORTANT             2136
#define IDC_RADIO_RESERVED              2137
#define IDC_AUTO_ADJUST                 2138
#define IDC_COMBO_CX                    2140
#define IDC_COMBO_CC                    2141
#define IDC_COMBO_ZY                    2142
#define IDC_COMBO_JJ                    2143
#define IDC_EDIT_SPEED                  2144
#define IDC_EDIT_TRAIN_ID               2145
#define IDC_EDIT_ENGINE                 2146
#define IDC_EDIT_MOTOMAN                2147
#define IDC_SEND                        2149
#define IDC_COMBO_DIRECTION             2155
#define IDC_DATETIMEPICKER              2155
#define IDC_STATIC_HAT                  2155
#define IDC_COMBO_UPDOWNPOS             2156
#define IDC_RADIO_IN                    2156
#define IDC_COMBO_DIRECTIONS            2156
#define IDC_STATIC_GRAPH                2156
#define IDC_RADIO_OUT                   2157
#define IDC_GRAPHIC_TRAIN               2157
#define IDC_COMBO_LINEPOS               2158
#define IDC_HAT_TRAIN                   2158
#define IDC_COMBO_DATASOURCE            2160
#define IDC_EDIT_DATE                   2162
#define IDC_PREVIOUS                    2163
#define IDC_STATIC_BOX                  2163
#define IDC_STATIC_FRAME                2164
#define IDC_NEXT                        2164
#define IDC_STATIC_BOX1                 2164
#define IDC_STATISTIC                   2165
#define IDC_USERID                      2165
#define IDC_PRINT                       2166
#define IDC_CONSOLEID                   2166
#define IDC_RADIO_ALL                   2167
#define IDC_USERNAME                    2167
#define IDC_STATIC_Grid                 2167
#define IDC_PASSWORD                    2168
#define ID_PRINT                        2168
#define IDC_BANBIE                      2170
#define IDC_COMBO_SECTION               2170
#define IDC_CUR_TIME                    2171
#define IDC_GRID_CTRL                   2171
#define IDC_PHASE1                      2172
#define IDC_CUR_DATE2                   2173
#define IDC_RADIO_REM                   2174
#define ID_SEND_CURRENT2                2174
#define IDC_DRIVER_NAME                 2174
#define IDC_COMBO3                      2175
#define IDC_COMBO_DERECTION             2175
#define IDC_TRACTION_ENGINE1            2175
#define IDC_COMBO_SHUZHI                2176
#define IDC_COMBO_TYPE                  2176
#define IDC_COMBO_WEATHER_END           2176
#define IDC_TRACTION_ENGINE2            2176
#define IDC_ATTACH_ENGINE1              2177
#define IDC_EDIT_CONTENT                2178
#define IDC_TRAIN_LEADER_NAME           2178
#define IDC_EDIT9                       2179
#define IDC_ATTACH_ENGINE2              2179
#define IDC_K_COUNT                     2180
#define IDC_COMBO_WEATHER_START         2181
#define IDC_ATTACH_ENGINE3              2181
#define IDC_PK_COUNT                    2182
#define IDC_S_METER                     2183
#define IDC_CK_COUNT                    2183
#define IDC_E_METER                     2184
#define IDC_PIK_COUNT                   2184
#define IDC_E_KILO                      2185
#define IDC_GK_COUNT                    2185
#define IDC_O_COUNT                     2186
#define IDC_STATIC_MESSAGE              2187
#define IDC_S_COUNT                     2187
#define IDC_TOTAL_COUNT                 2188
#define IDC_CAL_LEN                     2189
#define IDC_TOTAL_WEIGHT                2190
#define IDC_SCST_CARRIAGE_STYLE         2191
#define IDC_COVER                       2191
#define IDC_TAIL_NO                     2192
#define IDC_DEL                         2193
#define IDC_ATTACH_ENGINE4              2193
#define IDC_NOTEBOOK                    2193
#define IDC_EDIT_SIDE                   2194
#define IDC_EDIT                        2194
#define IDC_PHASE2                      2194
#define IDC_PHASE3                      2195
#define IDC_COMBO_SHUAI                 2197
#define IDC_DIRECTION_UP                2197
#define IDC_LIST_CONTENT                2198
#define IDC_DIRECTION2                  2198
#define IDC_DEST                        2199
#define IDC_CMB_STATION                 2200
#define IDC_ADD                         2201
#define IDC_SBT_BASIC_TRAIN             2201
#define IDC_DELETE                      2202
#define IDC_SBT_DAIMAO_TRAIN            2202
#define IDC_PZ_COUNT                    2203
#define IDC_GRID_STATUS                 2204
#define IDC_CZ_COUNT                    2204
#define IDC_PIZ_COUNT                   2205
#define IDC_CMB_NEIGHBER                2206
#define IDC_GZ_COUNT                    2206
#define IDC_NEW                         2207
#define IDC_COMBO_DDTNAME               2208
#define IDC_EDIT_COMMANDER              2209
#define IDC_FIND_TRAIN                  2209
#define IDC_FIND_RESULT                 2210
#define IDC_TRAIN_ID_F                  2211
#define IDC_CHANGE                      2212
#define IDC_DIRECTION_ALL               2213
#define IDC_SAVE                        2214
#define IDC_CMB_SHIFTID                 2214
#define IDC_EDIT_TIME                   2215
#define IDC_SAVE_MODIFY                 2215
#define IDC_PRINT_GROUP                 2215
#define IDC_SAVE2                       2215
#define IDC_EDIT_SEND_TIME              2216
#define IDC_STATIC_FIRST                2216
#define IDC_SPIN1                       2217
#define IDC_RADIO_NOTHING               2217
#define IDC_STATIC_SECOND               2217
#define IDC_GPC_NETMAP                  2218
#define IDC_SPIN2                       2218
#define IDC_RADIO_MARK                  2218
#define IDC_EDIT_TIME_EX                2218
#define IDC_LOCK_PRESTATION             2219
#define IDC_RADIO_LINE                  2219
#define IDC_LOCK_NEXTSTATION            2221
#define IDC_BUTTON_BEGINSTATISTICS      2221
#define IDC_COMBO_TEXTPOS               2222
#define IDC_BUTTON_RESTATISTICS         2222
#define IDC_COMBO_STATIONLIST           2223
#define IDC_TOTAL_SUM                   2225
#define IDC_DATETIMEEND1                2225
#define IDC_SEARCH                      2226
#define IDC_TOTAL_SUM1                  2227
#define IDC_EDIT_STARTTIME              2227
#define IDC_COMBO_STRREASON             2227
#define IDC_TOTAL_SUM2                  2228
#define IDC_EDIT_ENDTIME                2228
#define IDC_TOTAL_SUM3                  2229
#define IDC_GRID_TRAIN_TIME             2229
#define IDC_TOTAL_SUM4                  2230
#define IDC_CHECK_DATASHOW              2230
#define IDC_TOTAL_SUM5                  2231
#define IDC_DATETIMESTART1              2231
#define IDC_TOTAL_SUM7                  2232
#define IDC_COMBO_TRAINDIRECTION        2232
#define IDC_TOTAL_SUM6                  2233
#define IDC_COMBO_TRAINTYPE             2233
#define IDC_TOTAL_SUM10                 2234
#define IDC_COMBO_SORT                  2234
#define IDC_TOTAL_SUM11                 2235
#define IDC_CHECK_SPECIFIEDTRAINSHOW    2235
#define IDC_TOTAL_SUM12                 2236
#define IDC_STATIC_TITLE1               2236
#define IDC_TOTAL_SUM13                 2237
#define IDC_STATIC_SGCCONTENT1          2237
#define IDC_TOTAL_SUM14                 2238
#define IDC_TOTAL_SUM15                 2239
#define IDC_TOTAL_SUM16                 2240
#define IDC_BUTTON_CLOSE                2240
#define IDC_TOTAL_SUM8                  2241
#define IDC_STATISTICS_LOADSCHEDULE     2241
#define IDC_TOTAL_SUM9                  2242
#define IDC_STATIC_TRAVELINGTIME        2242
#define IDC_TOTAL_SUM17                 2243
#define IDC_CHECK_SORT_BYSUB            2243
#define IDC_TOTAL_SUM18                 2244
#define IDC_CHECK_SORTTRAINID           2244
#define IDC_BUTTON_SELALL               2244
#define IDC_BUTTON_LOAD                 2244
#define IDC_TOTAL_SUM31                 2245
#define IDC_BUTTON_DATASEND             2245
#define IDC_TOTAL_SUM30                 2246
#define IDC_RADIO_AUTO_LOCK_TRAIN       2246
#define IDC_STATIC_LINEBOX              2247
#define IDC_TOTAL_SUM33                 2247
#define IDC_RESEND_PLAN_SELECTED        2247
#define IDC_CHECK_AUTOREFRESH           2247
#define IDC_TOTAL_SUM34                 2248
#define IDC_NEW_PLAN                    2248
#define IDC_WORD_ADD                    2248
#define IDC_TOTAL_SUM32                 2249
#define IDC_WORD_EDIT                   2249
#define IDC_TOTAL_SUM35                 2250
#define IDC_WORD_DELETE                 2250
#define IDC_EDIT_NEW_WORD               2251
#define IDC_STATIC_GROUP                2251
#define IDC_EDIT_DETAIL                 2252
#define IDC_EDIT_TITLE                  2253
#define IDC_CHANGE_HATID                2255
#define IDC_CMB_MODULE                  2255
#define IDC_BUTTON_NOTSELALL            2256
#define IDC_CHECK_GENBAN2               2257
#define IDC_SHOW_LOCK_FLAG              2258
#define IDC_BTN_IMPORT                  2259
#define IDC_DATETIMER1                  2265
#define IDC_DTPICKER_ENDTIME            2266
#define IDC_DATETIMER2                  2266
#define IDC_STATIC_TIME                 2267
#define IDC_START_STA                   2278
#define IDC_END_STA                     2279
#define IDC_ENGINE_ID                   2282
#define IDC_CHECK_STPC                  2282
#define IDC_CHECK_LIRC                  2283
#define IDC_STATUS                      2284
#define IDC_CONTINUE                    2288
#define IDC_STOP                        2289
#define IDC_DATETIMEPICKER_START        2290
#define IDC_DATETIMEPICKER_END          2291
#define IDC_RADIO_UP                    2292
#define IDC_RADIO_DOWN                  2293
#define IDC_PRINT_FLAG                  2296
#define IDC_MESSAGE                     2298
#define IDC_CMB_STA                     2299
#define IDC_DETAILS                     2300
#define IDC_FOR_GRID                    2301
#define IDC_SHUAI                       2302
#define IDC_GUA                         2303
#define IDC_FRAME                       2304
#define IDC_USERNAME32                  2305
#define IDC_RADIO_ROUNDNONE             2306
#define IDC_RADIO_ROUNDRED              2307
#define IDC_RADIO_ROUNDBLUE             2308
#define IDC_MODE_STATUS                 2309
#define IDC_RADIO_CIRCLE                2309
#define IDC_RADIO_CIRCLE2               2310
#define IDC_BTN_DELETE                  2334
#define IDC_BTN_MOVEUP                  2335
#define IDC_BTN_MOVEDOWN                2336
#define IDC_BTN_CLOSE                   2352
#define IDC_BTN_MODIFY_SAVE             2363
#define IDC_BTN_INSERT_TO_GRAPH         2364
#define IDC_COMBO_BEGIN_ABS             2365
#define IDC_COMBO_END_ABS               2366
#define IDC_BTN_CANCEL_OPER             2367
#define IDC_RADIO_SJXY                  2374
#define IDC_RADIO_SYXY                  2375
#define IDC_RADIO_SJXJ                  2376
#define IDC_RADIO_SYXJ                  2377
#define IDC_EDIT_TIANCHUANG_NAME        2378
#define IDC_BTN_ADD_SAVE                2379
#define IDC_CHECK_INCLUDE_UP            2380
#define IDC_CHECK_INCLUDE_DOWN          2381
#define IDC_EDIT_TIANCHUANG_NO          2382
#define IDC_DTPICKER_BEGINTIME          2383
#define IDC_BUTTON_DIR                  2387
#define IDC_FILE_NAME                   2388
#define IDD_DLG_GIVEOUT_DIRECTION       2388
#define IDC_LIST_DETAIL                 2389
#define IDC_BEGIN_READ                  2390
#define IDC_EDIT_SHOW_TCCSTRING         2395
#define IDC_PROGRESS_STATUS             2396
#define IDC_STATIC_PROMPT               2401
#define IDC_ARRIVAL_ALL                 2402
#define IDC_DEPART_ALL                  2403
#define IDC_CHECK_SIDE                  2405
#define IDC_CHECK_ENTRY                 2406
#define IDC_CHECK_TENICALSTOP           2407
#define IDC_COMBO_REASON                2408
#define IDC_COMBO_TITLE                 2409
#define IDC_COMBO2                      2410
#define IDC_COMBO_TRAINID               2410
#define IDC_COMBO_POINT                 2411
#define IDC_COMBO_SIDE                  2412
#define IDC_AUTO                        2413
#define IDC_CBO_TIME_RANGE              2414
#define IDC_CLEAR_ALARM                 2415
#define IDC_LIST_CONTENT_TIDS           2423
#define IDC_CHANGE_TRAINID              2425
#define IDD_ABS_ELE_FIX_MANAGE          2426
#define IDC_LIST_CONTENT_ELE_FIX        2427
#define IDD_DLG_CZH_MULTI_EDIT          2427
#define IDC_BUTTON4                     2428
#define IDD_DIG_PART_RUN_TRAIN          2429
#define IDC_SET_SIDE_LOCK               2502
#define IDC_CLOSE                       2503
#define IDC_GRID_TRAIN                  2504
#define IDC_SET_SIDE_UNLOCK             2505
#define ID_MODIFY_TRAINS_CLOSE          2516
#define IDC_BUFFER_PERCENT              2532
#define IDC_FIND_TRAINS                 2533
#define IDC_MODIFY_TRAINS               2534
#define IDC_GRID                        11004
#define IDC_GRID2                       11005
#define IDC_LIST_MSG                    12056
#define IDC_CHECK_AUTOCLOSE             31011
#define ID_MARK_COPY_V_DOWN             32112
#define ID_MARK_COPY_V_UP               32113
#define ID_ONLY_SHOW_TRAIN              32773
#define ID_ONLY_SHOW_MARK               32774
#define ID_SHOW_MARK_AND_TRAIN          32775
#define ID_DEL_MULTI_TRAIN              32776
#define ID_DEFINE_COLOR                 32777
#define ID_SEL_MULTI_TRAIN              32778
#define ID_MODIFY_MULTI_TRAIN           32779
#define ID_SHOW_SINGLE_TRAIN            32780
#define ID_BLOCK_ADJUST_TRAINS          32958
#define ID_DELETE_ABS                   32959
#define ID_EXIT_DRAW_MARK_STATE         32960
#define ID_EXIT_DRAW_TRAIN_STATE        32961
#define ID_MODIFY_TRAIN_INDEX           32962
#define ID_SHOW_STATION_SIDES           32974
#define ID_MARK_PROPERTY                32975
#define ID_MARK_TIMESPAN                32976
#define ID_TRAIN_WORK_PLAN              32997
#define ID_UP_TRAIN                     32998
#define ID_DOWN_TRAIN                   32999
#define ID_DUAL_TRAIN                   33000
#define ID_PASEEGE_TRAIN                33001
#define ID_GOODS_TRAIN                  33002
#define ID_PESSGOODS_TRAIN              33003
#define ID_BASIC_BEGIN_TIME_18          33005
#define ID_BASIC_BEGIN_TIME_12          33006
#define ID_SHOW_ROUTE_STATUS            33007
#define ID_MODIFY_TRAIN_CZH             33008
#define ID_SHOW_CZH_TRAIN               33009
#define ID_GOULIAN_TRAIN_BY_CZH         33011
#define ID_GENTRAINID_BY_CZH            33012
#define ID_DIRECT_SET_TRIG              33015
#define ID_SHOW_BASIC_INFO              33016
#define ID_MARK_CANCELWORK              33017
#define ID_TRAIN_SUBAO_INFO             33018
#define ID_TRAIN_WORK_INFO              33019
#define ID_MARK_WORK_INFO               33020
#define ID_MODIFY_PLAN_PARA             33021
#define ID_CHANGE_TRACK                 33022
#define ID_STOP_DWAW                    33023
#define ID_CONTINUE_DRAW                33024
#define ID_PASS_TO_STAY                 33025
#define ID_CANNOT_MEET                  33026
#define ID_TRAINSPORT_INFO              33027
#define ID_QUERT_QUEBAO                 33028
#define ID_FIND_DDML                    33029
#define ID_STOP_ABS                     33030
#define ID_STOP_ABS_CANCEL              33031
#define ID_STOP_SIGNAL                  33032
#define ID_STOP_SIGNAL_CANCEL           33033
#define ID_TRAIN_ATTRIBUTE              33034
#define ID_CHANGE_TRAINID               33035
#define ID_ADDTRAIN_STOP                33036
#define ID_ADDTRAIN_DELIVER             33037
#define ID_ADDTRAIN_ABS_STOP            33038
#define ID_MUTI_STAY_TO_PASS            33039
#define ID_TRAIN_BIANZU_INFO            33040
#define ID_TRAIN_ENGINE_INFO            33041
#define ID_JIECHU_TRAIN_CZH             33042
#define ID_KAKONG_BASIC_SIDE            33043
#define ID_KAKONG_BASIC_ENTRY           33044
#define ID_DELETE_TRAIN                 33054
#define ID_TRAIN_COPY                   33055
#define ID_REPLACE_TRAINID              33071
#define ID_STATISTIC_ARRIVAL            33072
#define ID_STATISTIC_DEPART             33073
#define ID_STATISTIC_BOTH               33074
#define ID_NO_STATISTIC                 33075
#define ID_BASIC_INFO                   33085
#define ID_TRAIN_DATA                   33096
#define ID_LOCK_STATION_SIDE            33097
#define ID_LOCK_TRAIN_SIDE              33098
#define ID_DETAIL_PROPERTY              33115
#define ID_MIDDLE_START                 33118
#define ID_MIDDLE_FETCH                 33119
#define ID_ADJUST_BEGIN                 33120
#define ID_ADJUST_END                   33125
#define ID_ABS_TRAIN_BEGIN              33126
#define ID_ABS_TRAIN_END                33129
#define ID_ADJUST_SINGLE                33135
#define ID_GUA_JICHE                    33136
#define ID_DIVIDEPORT_LATETIME          33137
#define ID_STOP_DEPART                  33145
#define ID_PRESS_BEFORE                 33146
#define ID_PRESS_AFTER                  33148
#define ID_MIDDLE_DIVIDE                33150
#define ID_MARK_CONTINUE_LINING         33156
#define ID_MARK_MOVE_START              33157
#define ID_MARK_MOVE_STOP               33158
#define IDC_DISPATCHER_INPUT            33159
#define ID_ADJUST_SINGLE_EX             33169
#define ID_SUBAO_QUERY                  33175
#define ID_SHUAIGUA_MANAGE              33176
#define ID_QUEBAO                       33178
#define ID_MARK_PLAN                    33180
#define ID_MARK_ACTIVE                  33181
#define ID_MARK_COMPLETE                33182
#define ID_BASIC_TRAINPASTE             33201
#define ID_SHOWTRACTION_NO              33208
#define ID_SHOWTRACTION_TOP             33209
#define ID_SHOWTRACTION_MIDDLE          33210
#define ID_SHOWTRACTION_BOTTOM          33211
#define ID_STOP_TEMP                    33212
#define ID_REFUSEED_TRAIN               33213
#define ID_STATISTIC_WHOLE              33214
#define ID_MARK_COPY                    33216
#define ID_MIDDLE_DIV_TRAIN             33217
#define ID_REPLACE_HATTRAINID           33243
#define ID_ADD_TO_SCHEDULE              33267
#define ID_STOP_DRAW_UP                 33275
#define ID_STOP_DRAW_MIDDILE            33276
#define ID_STOP_DRAW_BOTTOM             33277
#define ID_TO_DISPATCH                  33397
#define ID_DEFINE_PASS                  33400
#define ID_TECH_STOP                    33401
#define ID_SAVE_TRAIN_XML               33402
#define ID_SET_SECRET_TRAIN             33403
#define ID_SET_NO_LATE_TIME             33404
#define ID_SET_ERROR_SIDE               33405
#define IDC_SPLITED_TRAIN               39333
#define IDC_SPLIT_FIRST_TRAIN           39334
#define IDC_SPLIT_SECOND_TRAIN          39335
#define IDC_BTN_SPLIT_OK                39336
#define IDC_BTN_SPLIT_CANCEL            39337
#define IDC_COMBINED_FIRST_TRAIN        39401
#define IDC_COMBINED_SECOND_TRAIN       39402
#define IDC_COMBINE_FINISHED_TRAIN      39403
#define IDC_BTN_COMBINE_OK              39404
#define IDC_BTN_COMBINE_CANCEL          39405
#define ID_BATCH_MODIFY_TRACK           39406
#define ID_INHBIT_PASS                  39407
#define IDC_CHECKBOX_START              40000
#define IDC_CHECK1                      50001
#define IDC_CHECK                       50001
#define IDC_CHECK2                      50002
#define IDC_CHECK3                      50003
#define IDC_CHECK4                      50004
#define IDC_CHECK5                      50005
#define IDC_CHECK6                      50006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        265
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         259
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
