//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TCC_C3.rc
//
#define IDC_BeginLimit                  3
#define IDC_EndLimit                    4
#define IDC_TCC_CMD_CONTENT             1000
#define IDC_BTN_TCCCMD_TRY_EXECUTE      1002
#define IDC_TCC_LINE_STATUS_GRID        1003
#define IDC_TCC_CANCELCOMMAND           1004
#define IDC_EDIT_TCCCMDCONTENT          1005
#define IDC_EDIT_TCCCMDSTATUS           1006
#define IDC_CHECK1                      1007
#define IDC_TCC_CMD_TCC                 1008
#define IDC_RADIO1                      1010
#define IDC_RADIO2                      1011
#define IDC_RADIO3                      1012
#define IDC_BTN_TCCCMD_SKETCHMAP        1013
#define IDC_SKETCH_MAP                  1013
#define IDC_TCC_COMMAND_EDIT            1015
#define IDC_TCC_COMMAND_VALID           1016
#define IDC_TCC_COMMAND_NEW             1017
#define IDC_STATUS                      1018
#define IDC_TEXT                        1021
#define IDC_EDIT1                       1024
#define IDC_CHANGE_TCCCMDID             1025
#define IDC_AUTOCOMPUTE_TCCCMDID        1026
#define IDD_PASSWORD                    1117
#define IDC_TCC_REFRESH_STATIONLIST     2319
#define IDC_TCC_LIST                    2320
#define IDC_TCC_STATUS                  2321
#define IDC_TCC_CMD_TRAINID             2322
#define IDC_TCC_CMD_TRAINID2            2323
#define IDC_TCC_CMD_TRAINID3            2324
#define IDC_TCC_CMD_TRAINID4            2325
#define IDC_TCC_CMD_TRAINID5            2326
#define IDC_TCC_CMD_LIMITVAL            2327
#define IDC_TCC_CMD_LIMITVAL2           2328
#define IDC_TCC_CMD_LIMITVAL3           2329
#define IDC_TCC_CMD_LIMITVAL4           2330
#define IDC_TCC_CMD_LIMITVAL5           2331
#define IDC_TCC_LIMIT                   2332
#define IDC_TCC_LIMIT2                  2333
#define IDC_TCC_LIMIT3                  2334
#define IDC_TCC_LIMIT4                  2335
#define IDC_TCC_LIMIT5                  2336
#define IDC_TCC_CMD_PASSITIVESTA        2336
#define IDC_TCC_LIMIT6                  2337
#define IDC_TCC_CREATECMD_BTN           2343
#define IDC_TCC_SAVECMD_BTN             2344
#define IDC_TCC_SENDCMD_BTN             2345
#define IDC_TCC_DELCMD_BTN              2346
#define IDC_TCC_CANCELCMD_BTN           2347
#define IDC_TCC_CMD_LIMIT_MODE          2348
#define IDC_TCC_CMD_LIMIT_MODE2         2349
#define IDC_TCC_CMD_LIMIT_MODE3         2350
#define IDC_TCC_REFRESH                 2351
#define IDC_TCC_CMD_LIST                2352
#define IDC_TCC_CMDID                   2353
#define IDC_TCC_INIT_COMPLETE           2353
#define IDC_TCC_CMD_STA                 2354
#define IDC_TCC_COMMAND_FULLCANCEL      2354
#define IDC_TCC_CMD_STA2                2355
#define IDC_TCC_CMD_ABSLINE             2356
#define IDC_TCC_CMD_KM                  2357
#define IDC_TCC_CMD_M                   2358
#define IDC_TCC_CMD_KM2                 2359
#define IDC_TCC_CMD_M2                  2360
#define IDC_TCC_CMD_ADJUST_KM           2361
#define IDC_TCC_CMD_TIMEBEGIN           2362
#define IDC_TCC_CMD_TIMEBEGIN_RADIO     2363
#define IDC_TCC_CMD_TIMEBEGIN_RADIO2    2364
#define IDC_TCC_CMD_TIMEEND             2365
#define IDC_TCC_CMD_TIMEEND_RADIO       2366
#define IDC_TCC_CMD_TIMEEND_RADIO2      2367
#define IDC_TCC_CMD_TYPE                2368
#define IDC_TCC_CMD_ACTIVEUNIT          2368
#define IDC_TCC_CMD_ACTIVEPERSON        2369
#define IDC_TCC_CMD_VALID_KM            2369
#define IDC_TCC_CMD_ACTIVETIME          2370
#define IDC_TCC_CMD_STATUS              2371
#define IDC_TCC_CMD_PASSITIVESTA2       2372
#define IDC_TCC_CMD_STATUS2             2373
#define IDC_TCC_STATUS_LIST             2378
#define IDC_TCC_TEXT                    2379
#define IDC_TCC_CMD_NOTE                2391
#define IDC_TCC_CANCE_LIMIT             2392
#define IDC_TAB1                        2394
#define IDC_TCC_COMMAND_SEND            2395
#define IDC_LS_SKETCHMAP                2396
#define IDR_TCC                         3101
#define IDD_TCC                         3102
#define IDD_DLG_SKETCH_MAP              3103
#define IDD_DIRECT_LIMIT                3104
#define IDD_TCCCOMMAND_STATUS_CHANGE    3105
#define IDD_TCC_CONFIRM_COMMAND         3108
#define IDD_TCC_LOCALCMD_MGR            3109
#define IDD_TCC_LIRC_CMD_TABLE          3110
#define IDD_TCC_LIMITSPEED_CONFIRM      3111
#define IDD_TCC_COMMAND_INPUT           3112
#define IDD_DLG_TCC_COMMAND_SEND        3113
#define IDD_DLG_TCC_COMMAND_FULLCANCEL  3114
#define IDD_DLG_TCCDIRECTCMD            3115
#define IDD_TCC_COMMAND_INPUT2          3116
#define IDD_TCC_HISTORY_COMMAND         3117
#define IDD_CMD_TYPE_SELECT             3118
#define IDC_TCC_CMD_LONGKM              3336
#define IDC_TCC_CMD_LONGKM2             3337
#define IDC_TCC_CMD_LONGM               3338
#define IDC_TCC_CMD_LONGM2              3339
#define IDC_BTN_TCCDNEW                 3464
#define IDC_BTN_ADJUST_ACK              3465
#define IDC_BTN_TCCDCHECK               3466
#define IDC_BTN_TCCDSEND                3468
#define ID_CANCEL_LIMITSPEED            40010
#define ID_SEND_LIMITSPEED              40011
#define ID_DEL_STOCKCOMMAND             40012
#define ID_CANCEL_LIMITSPEED_DIRECT     40014
#define ID_DEL_PARTIAL_STOCKCOMMAND     40015
#define ID_DEL_RAWSTOCKCOMMAND          40016
#define ID_TCCCOMMAND_STATUS_CHANGE     40018

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        3119
#define _APS_NEXT_COMMAND_VALUE         40019
#define _APS_NEXT_CONTROL_VALUE         1026
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
