
#ifndef  __MSGID_H__
#define  __MSGID_H__

enum {
	MSGID_DEFAULT  = 0,
	MSGID_BASEMSG = 1,
	
	MSGID_MsgDSSDisplay=2,
	MSGID_MsgTrainNoOper=3,
	MSGID_MsgTrainConfirm=4,
	MSGID_MsgStationDown=5,
	MSGID_MsgStationUp=6,
	MSGID_MsgManualButtonPress=7,
	MSGID_MsgManualButtonCancel=8,
	MSGID_MsgManualRouteSet=9,
	MSGID_MsgHILCTransmit=10,
	
	MSGID_MsgManualDeviceOper=12,
	MSGID_MsgManualRouteTryLock=13,
	MSGID_MsgSetTrainAttrib=14,
	MSGID_MsgManualOperResult=15,
	MSGID_MsgStationModeRequest=16,
	MSGID_MsgStationModeResult=17,
	MSGID_MsgRouteModeRequest=18,
	MSGID_MsgRouteModeResult=19,
	MSGID_MsgStationModeReport=20,
	MSGID_MsgStationCTCFlagSet=21,
	MSGID_MsgRouteListRequest=22,
	MSGID_MsgRouteListRelease=23,
	MSGID_MsgRouteListResult=24,
	MSGID_MsgRouteUpdate=25,
	MSGID_MsgRouteInsert=26,
	MSGID_MsgRouteDelete=27,
	MSGID_MsgRouteMove=28,
	MSGID_MsgRouteTrig=29,
	MSGID_MsgRouteOperResult=30,
	MSGID_MsgRouteLongInfo=31,
	MSGID_MsgRouteShortInfo=32,
	MSGID_MsgRouteInfoDel=33,
	MSGID_MsgRouteInfoMove=34,
	MSGID_MsgBitblock=35,
	MSGID_MsgIndiChange=36,
	MSGID_MsgMasterStatus=37,
	MSGID_MsgAlarm=38,
	MSGID_MsgLogin=39,
	MSGID_MsgLoginReply=40,
	MSGID_MsgEntityConnStatus=41,
	MSGID_MsgGpcAccessInfo=42,
	MSGID_MsgGpcAccessReply=43,
	MSGID_MsgGpcLogin=44,
	MSGID_MsgReportTime=45,
	MSGID_MsgReportTrainId=46,
	MSGID_MsgStPlanSendOrder=47,
	MSGID_MsgStPlanStatusRequest=48,
	MSGID_MsgStPlanStatusAnswer=49,
	MSGID_MsgStPlanSendInit=50,
	MSGID_MsgStPlanInsert=51,
	MSGID_MsgStPlanDelete=52,
	MSGID_MsgStPlanSendComplete=53,
	MSGID_MsgStPlanTrainRecv=54,
	MSGID_MsgStPlanRecvALL=55,
	MSGID_MsgShuntNoteInit=56,
	MSGID_MsgShuntNoteComplete=57,
	MSGID_MsgShuntNoteSendOrder=58,
	MSGID_MsgShuntNoteRecvALL=59,
	MSGID_MsgShuntNoteDelete=60,
	MSGID_MsgShuntNoteInsert=61,
	MSGID_MsgShuntNoteUpdate=62,
	MSGID_MsgShuntNoteListRequest=63,
	MSGID_MsgShuntNoteListInit=64,
	MSGID_MsgShuntNoteListComplete=65,
	MSGID_MsgShuntNoteRequest=66,
	MSGID_MsgShuntNoteStatus=67,
	MSGID_MsgShuntNoteHead=68,
	MSGID_MsgShuntNoteGou=69,
	MSGID_MsgShuntNoteRouteList=70,
	MSGID_MsgShuntNoteStoreCar=71,
	MSGID_MsgShuntNotePicture=72,
	MSGID_MsgShuntStatusUpdate=73,
	MSGID_MsgGpcMsgEcho=74,
	MSGID_MsgHugeDataCtrl=75,
	MSGID_MsgBasicTrainListInit=76,
	MSGID_MsgBasicTrainListReply=77,
	MSGID_MsgDssDisplayOrder=78,
	MSGID_MsgEntityConnStatusOrder=79,
	MSGID_MsgTimeSync=80,
	MSGID_MsgSimButton=81,
	MSGID_MsgCTCOutput=82,
	MSGID_MsgShuntNoteGpcOperEcho=83,
	MSGID_MsgDssInitComplete=84,
	MSGID_MsgStPlanRequest=85,
	MSGID_MsgStPlanAutoTrigUpdate=86,
	MSGID_MsgLoadTrainFormRequest=87,
	MSGID_MsgLoadAsmTrainFormHead=88,
	MSGID_MsgLoadAsmTrainForm=89,
	MSGID_MsgLoadTrainFormResponse=90,
	MSGID_MsgUpdateSscRequest = 91,
	MSGID_MsgUpdateSscRequestEnd = 92,
	MSGID_MsgUpdateSscResponse = 93,
	MSGID_MsgUpdateSscResponseEnd = 94,
	MSGID_MsgLoadSscRequest=95,
	MSGID_MsgLoadSscResponse=96,
	MSGID_MsgLoadSscBlock=97,
	MSGID_MsgUpdateSscBlock=98,
	MSGID_MsgUpdateSscBlockPos=99,
	MSGID_MsgUpdateSscBlockStatus=100,
	MSGID_MsgUpdateSscBlockNote=101,
	MSGID_MsgDeleteSscBlock=102,
	MSGID_MsgInsertSscBlock=103,
	MSGID_MsgOperBlockReaponse=104,
	MSGID_MsgLoadSscCarriage=105,
	MSGID_MsgUpdateSscCarriage=106,
	MSGID_MsgDeleteSscCarriage=107,
	MSGID_MsgInsertSscCarriage=108,
	MSGID_MsgOperSscCarriageReaponse=109,
	MSGID_MsgNextPlanSendOrder=110,
	MSGID_MsgNextPlanRequest=111,
	MSGID_MsgNextPlanSendInit=112,
	MSGID_MsgNextPlanSendComplete=113,
	MSGID_MsgNextPlanInsert=114,
	MSGID_MsgNextPlanTrainRecv=115,
	MSGID_MsgNextPlanRecvStatus=116,
	MSGID_MsgNextPlanSignStatus=117,	
	MSGID_MsgWordPhasePlanSend=118,
	MSGID_MsgWordPhasePlanStatus=119,
	MSGID_MsgWordPhasePlanQuery=120,
	MSGID_MsgSubaoFormat=121,	
	MSGID_MsgSubaoQuery=122,	
	MSGID_MsgSimpleStationCarFormat=123,
	MSGID_MsgSimpleStationCarCtrl=124,
	MSGID_MsgSimpleStationCarQuery=125,
	MSGID_MsgSimpleStationCarConvert=126,
	MSGID_MsgNotePadFormat=127,
	MSGID_MsgNotePadQuery=128,
	MSGID_MsgAccidentOper=129,
	MSGID_MsgAccidentQuery=130,
	MSGID_MsgAlarmEx = 131,
	MSGID_MsgUserManager = 132,
	MSGID_MsgUserManagerQuery = 133,
	MSGID_MsgRouteStatusInform = 134,
	MSGID_MsgGroupTrainWorkFormat = 135,
	MSGID_MsgGroupTrainWorkDel = 136,
	MSGID_MsgGroupTrainWorkQuery = 137,
	MSGID_MsgDispatchCommandSend = 138,
	MSGID_MsgDispatchCommandStatus = 139,
	MSGID_MsgAdjustSequenceLoad = 140,
	MSGID_MsgAdjustSequenceData = 141,
	MSGID_MsgAutoAdjustInform = 142,
	MSGID_MsgAutoAdjustSingleInform = 143,
	MSGID_MsgAutoAdjustUndo = 144,
	MSGID_MsgRouteInfoRefresh = 145,
	
	MSGID_MsgLiRCStatusReport = 147,
	MSGID_MsgTrainDepartTime = 148,
	MSGID_MsgIPTrainOper	= 149,
	MSGID_MsgStationModeQuery = 150,
	MSGID_MsgDataStyleReq = 151,
	MSGID_MsgShuntNoteSend2Lirc = 152,
	MSGID_MsgShuntNote2LocoMotiveStatus = 153,
	MSGID_MsgDataRequest = 154,
	MSGID_MsgServerProcessEcho = 155,
	MSGID_MsgQueryTrainForRoute = 156,
	MSGID_MsgAnswerTrainForRoute = 157,
	MSGID_MsgCommStatusReport = 158,
	MSGID_MsgPeerDetect = 159,
	MSGID_MsgRouteSideUpdate = 160,
	MSGID_MsgRouteButtonUpdate = 161,
	MSGID_MsgRouteGiveWayUpdate = 162,
	MSGID_MsgRouteTrigFlagUpdate = 163,
	MSGID_MsgRouteCompare = 164,
	MSGID_MsgManualDeviceOperEnable = 165,
	MSGID_MsgManualDeviceOperEx = 166,
	MSGID_MsgIconCTCStatus = 167,
	MSGID_MsgRouteGroupTrig = 168,
	MSGID_MsgRouteGroupOperResult = 169,
	MSGID_MsgShuntNoteSingleGouInit=170,
	MSGID_MsgShuntNoteSingleGouComplete=171,
	MSGID_MsgShuntNoteSingleGouRecvALL=172,
	MSGID_MsgDataStyleReq2 = 173,

	MSGID_MsgSetDDyName = 176,
	MSGID_MsgGetDDyName = 177,
	MSGID_MsgGiveDDyName = 178,
	MSGID_MsgDataStyleReq3 = 179,
	MSGID_MsgParamentOperation = 180,
	MSGID_MsgParamentRequest = 181,
	MSGID_MsgParamentReply   = 182,

	MSGID_MsgDataStyleReq4 = 183,	
	MSGID_MsgBasicScheduleSet = 184,
	MSGID_CmsMsgAttrRequest = 185,
	MSGID_CmsMsgSvrRegister = 186,
	MSGID_CmsMsgSingleAttrReply = 187,
	MSGID_CmsMsgGroupAttrReply = 188,
	MSGID_CmsMsgQueueAttrReply = 189,
	MSGID_CmsMsgAlarm = 190,
	MSGID_CmsMsgClientDevRegister = 191,
	MSGID_CmsMsgCapaAttrReply = 192,
	
	MSGID_IPMsgTrainMove = 200,
	MSGID_IPMsgRouteStatus  = 201,
	MSGID_IPMsgSideStatus  = 202,
	MSGID_IPMsgTrainStatus   = 203,
	
	//车站列控中心三点检查
	MSGID_MsgTccThreePointCheckRequest = 204,  //CTC->TCC
	MSGID_MsgTccThreePointCheckConfirm = 205,  //TCC->CTC

    MSGID_MsgBaseTrainPlan = 281,

	
	MSGID_MsgShuntTimeReport = 285,
	MSGID_MsgShuntRouteGroupRequest = 286,
	MSGID_MsgShuntLocoNoOper = 287,
	
	
	MSGID_GSMR_RADIOTRAINID=290,
	MSGID_GSMR_REQTDISPLAY=291,
	MSGID_GSMR_MOTIVEDEVALARM=292,
	MSGID_GSMR_ROUTEFORTELL=293,
	MSGID_GSMR_MOTIVEDISPLAY=294,
	MSGID_GSMR_TRAINIDUPDATE=295,
	MSGID_GSMR_TRAINOUTOFCONTROL=296,
	MSGID_GSMR_REQSHUNTNOTE=297,
	MSGID_GSMR_REPSHUNTNOTE=298,
	MSGID_GSMR_QUERYTRAINPOS=299,
	MSGID_GSMR_REPLYTRAINPOS=300,
	MSGID_GSMR_QUEPRESTATION=301,
	MSGID_GSMR_REPPRESTATION=302,
	MSGID_GSMR_LOCALMSG=303,
	MSGID_MsgStccCmdSend = 304,
	MSGID_MsgStccCmdStatus = 305,
	MSGID_MsgStccReport = 306,
	MSGID_MsgTccCommand = 307,
	MSGID_MsgTccCommandAdd = 308,
	MSGID_MsgTccCommandDel = 309,
	MSGID_MsgTccCommandDump = 310,
	MSGID_MsgTccCommandQuery = 311,
	MSGID_MsgStccCommandSend = 312,
	MSGID_MsgTccCommandStatusChanged =313,
	MSGID_MsgStccCommandSendResult = 314,
	MSGID_MsgStccCommandListQuery = 315,
	MSGID_MsgStccCommandList = 316,
	MSGID_MsgAlarmExd= 317,
	MSGID_MsgQueryLocomotiveInfo = 318,
	MSGID_MsgLocomotiveInfo = 319,
	MSGID_MsgElecArmSet   = 320,
	MSGID_MsgElecArmQuery = 321,
	MSGID_MsgElecArmAnswer= 322,
	MSGID_MsgPackRequest  = 323,
	MSGID_MsgCollector    = 324,
	MSGID_MsgPackAnswer   = 325,	
	MSGID_MsgDSSManualDeviceOper  = 326,
	MSGID_MsgTrainDelayTime = 327,
	MSGID_MsgRouteGroupUpdate = 328,
	MSGID_MsgRouteLongInfoNew = 329,
	MSGID_MsgSetTrainStop = 330,	
	MSGID_MsgDCmdTitle            = 331,
	MSGID_MsgDCmdSendList         = 332,
	MSGID_MsgDCmdContent          = 333,
	MSGID_MsgDCmdTcc              = 334,
	MSGID_MsgDCmdData             = 335,
	MSGID_MsgDCmdInsert           = 336,
	MSGID_MsgDCmdDelete           = 337,  
	MSGID_MsgDCmdTitleLoad        = 338,
	MSGID_MsgDCmdLoad             = 339,
	MSGID_MsgDCmdSend             = 340,
	MSGID_MsgDCmdRecv             = 341,
	MSGID_MsgDCmdCurrentNoRequest = 342,
	MSGID_MsgDCmdCurrentNo        = 343,
	MSGID_MsgDCmdStatus           = 344,
	MSGID_MsgDCmdRequest          = 345,
	MSGID_MsgDCmdAnswer           = 346,
	MSGID_MsgDCmdCurrentNoRequest2= 347,
	MSGID_MsgDCmdTcc2             = 348,

	MSGID_MsgGpcMessage  = 350,
	MSGID_MsgStccInitComplete=351,
	MSGID_MsgStccReport2 = 352,
	MSGID_MsgStccCommandList2 = 353,
	MSGID_MsgStccCommandSend2 = 354,
	MSGID_MsgTccCommand2 = 355,
	MSGID_MsgStccCommandSendResult2 = 356,
	MSGID_MsgTccCommandQuery2   = 357,
	MSGID_MsgTccCommandSet      = 358,
	MSGID_MsgTccCommandOperEcho = 359,
	MSGID_MsgTccCommandAdd2  = 360,
	MSGID_MsgTccCommandData2 = 361,
	MSGID_MsgDCmdTitleClose  = 362,    
	MSGID_MsgDCmdRefresh     = 363,
	MSGID_MsgDCmdLoad2       = 364,
	MSGID_MsgDcmd_BroadCast_Send	= 365,
	MSGID_MsgDcmd_BroadCast_Status	= 366,
	MSGID_MsgDcmd_BroadCast_Command = 367,
	MSGID_MsgDcmd_WirelessBroadcast = 368,
	MSGID_MsgWTrainInfo            = 369,
	MSGID_MsgWTrainRecord          = 370,
	MSGID_MsgWTrain                = 371,
	MSGID_MsgWTrainAdd             = 372,
	MSGID_MsgWTrainDelete          = 373,
	MSGID_MsgWTrainUpdate          = 374,
	MSGID_MsgWTrainData            = 375,
	MSGID_MsgWTrainComposeInfo     = 376,
	MSGID_MsgWTrainComposeAdd      = 377,
	MSGID_MsgWTrainComposeDelete   = 378,
	MSGID_MsgWTrainComposeUpdate   = 379,
	MSGID_MsgWTrainComposeData     = 380,

	MSGID_MsgChangeSideAck		   = 381,
	MSGID_MsgChangeSideReq		   = 382,

	MSGID_MsgTrainKediaoInfo	   = 390,
	MSGID_MsgTrainYingyeInfo	   = 391,
	MSGID_MsgTrainCrewInfo		   = 392,
	MSGID_MsgTrainPassgenerTicketInfo = 393,
	MSGID_MsgEngineCrewInfo		   = 394,
	MSGID_MsgTrainExpand		   = 395,
	MSGID_MsgTrainOPMSInfo		   = 396,
	MSGID_MsgTrainCmdInfo	   = 397,
	MSGID_MsgTrainExtent		   = 398,

	MSGID_MsgLiRCToGpc=400,
	MSGID_MsgDirectOutput=401,
	
	MSGID_MsgLiRCStatusReportNew	= 410,
	MSGID_MsgStccCommandDetail		= 411,
	MSGID_MsgStccCommandDetail2		= 412,
	MSGID_MsgStccCommandIDRequest	= 413,
	MSGID_MsgGsmrTrainInfo	= 414,

	MSGID_MsgNeibTrainUpdate   = 418,
	MSGID_MsgSchdStamp         = 419,
	MSGID_MsgTrainInfo         = 420,
	MSGID_MsgTrainEngineInfo   = 421,
	MSGID_MsgTrainAbsStop      = 422,
	MSGID_MsgTrainRecord       = 423,
	MSGID_MsgTrain             = 424,
	MSGID_MsgTrainAdd          = 425,
	MSGID_MsgTrainDelete       = 426,
	MSGID_MsgTrainUpdate       = 427,
	MSGID_MsgTrainUpdateInfo   = 428,
	MSGID_MsgTrainData         = 429,
	MSGID_MsgTrainUpdateEngine = 430,
	MSGID_MsgTrainUpdateRecord = 431,
	MSGID_MsgSchdBlock         = 432,
	MSGID_MsgSchdBlockAdd      = 433,
	MSGID_MsgSchdBlockUpdate   = 434,
	MSGID_MsgSchdBlockDelete   = 435,
	MSGID_MsgSchdBlockData     = 436,
	MSGID_MsgSchdMsgEcho       = 437,
	MSGID_MsgConvertBasicSchd  = 438,
	MSGID_MsgSchdLoad          = 439,
	MSGID_MsgNoticeNeigbourReceiveSchd  = 440,
	MSGID_MsgTrainRecordData   = 441,
	MSGID_MsgConvertBasicSchdNew  = 442,



	MSGID_MsgEventReg = 446,
	MSGID_MsgEventData = 447,
	MSGID_MsgEventReq = 448,


	MSGID_MsgRBCTrainInfo = 451,
	
	MSGID_MsgRBCAlarm = 453,
	MSGID_MsgRBCTrainOperation = 454,
	
	MSGID_MsgRBCStatusReport = 456,
	MSGID_MsgRBCEmergencySend = 457,
	MSGID_MsgRBCEmergencyResult = 458,
	MSGID_MsgRBCTxt = 459,
	MSGID_MsgRMRequest = 460,
	MSGID_MsgRMResult = 461,
	MSGID_MsgRMReport = 462,
	MSGID_MsgRMRegister = 463,
	MSGID_MsgRMOperPack = 464,

	MSGID_MsgTSRCmdSend = 471,
	MSGID_MsgTSRCmdSendResult = 472,
	MSGID_MsgTSRCmdStatus = 473,
	MSGID_MsgTSRCmdQuery = 474,
	MSGID_MsgTSRCmdCount = 475,
	MSGID_MsgTSRCmdDisplay = 476,
	MSGID_MsgTSRCmdOperation = 477,
	MSGID_MsgTSRCmdOperResult = 478,
	MSGID_MsgTSRCmdAlarm = 479,
	MSGID_MsgTSRServerStatus = 480,
	MSGID_MsgTSRServerRequest = 481,
	MSGID_CheckDupilicateTrainID = 482,
	MSGID_FindUniqeTrainID = 483,
	MSGID_CheckDupilicateTrainIDResult = 484,
	MSGID_FindUniqeTrainIDResult = 485,
	MSGID_GetTrainIDList = 486,
	MSGID_QueryTrainByID = 487,
	MSGID_MsgAlarmReg = 488,
	MSGID_MsgAlarmReq = 489,
	
	MSGID_MsgTrackCircuit = 492,
	MSGID_MsgDestEntityUpdate = 493,
	MSGID_MsgStPlanAutoTrigUpdateResult = 494,
	MSGID_MsgCISFIRAlarm = 495,
	MSGID_MsgTrainDepartPredict = 496,
	MSGID_MsgStringMessage2 = 497,
	MSGID_MsgReportTimeTransfer = 498,
	MSGID_MsgStringMessage = 499,

	MSGID_BASE=500, // 定义的MSGID值不得大于MSGID_BASE

	MSGID_MsgTrainRecordOCX       = 900,
	MSGID_MsgTrainOCX			  = 901,
	MSGID_MsgSchdBlockOCX		  = 902,

};

#define AR_WRITE_COUNT(count, a)           \
	{ar << count;                          \
	if (count >= sizeof(a)/sizeof(a[0])) return HRCODE(HRCODE::HC_FAIL);}

#define AR_READ_COUNT(count, a)            \
	{ar >> count;                          \
	if (count >= sizeof(a)/sizeof(a[0])) return HRCODE(HRCODE::HC_FAIL);}

#define AR_WRITE_STRING(s, len)    \
	{len = strlen((char*)s);       \
	ar << len;                     \
	ar.write((char*)s, len);}

#define AR_READ_STRING(s, len)                             \
	{ar >> len;                                            \
	if (len >= sizeof(s)) return HRCODE(HRCODE::HC_FAIL);  \
	ar.read(s, len);                                       \
	s[len] = 0;}

#define GET_STR_LEN(type, stri)   (sizeof(type)+strlen(stri))

#define MSG_DEF_VERSION   "1.2.11"
#define MSG_DEF_UPDATE_RECORD                                               \
"[V1.0.0 2013-12-09]:  对CTC各子系统使用的MsgDef进行统一强制性统一   \n"    \
"[V1.1.0 2013-12-09]:  扩展到64位平台   \n"                                 \
"[V1.2.0 2013-12-09]:  ctc_define增加权限UR_URGENCY_OPER   \n"              \
"[V1.2.1 2014-01-02]:  MsgDispatchCommandStatus::RECV_STATUS 增加COMMAND_AGREE与COMMAND_DISAGREE  \n"   \
"[V1.2.2 2014-01-02]:  MsgDispatchCommandStatus::RECV_STATUSenum缺少, basictypes.h 增加bit32/64\n"      \
"[V1.2.3 2014-02-13]:  basictypes.h IBOOL定义错误, 修改为I_BOOL\n"          \
"[V1.2.4 2014-03-21]:  增加event事件\n"                                     \
"[V1.2.5 2014-04-17]:  增加消息的注释\n"										\
"[V1.2.6 2014-05-30]:  增加BL与CTCi转发无线车次信息消息MsgGsmrTrainInfo\n" \
"[V1.2.7 2014-08-14]:  增加列控三点检查消息(ID:204/205)\n"                 \
"[V1.2.8 2015-03-20]:  扩展WintgTerm登录权限管理，修改MsgParamentRequest和MsgParamentReply的ID，增加MsgParamentOperation\n"		\
"[V1.2.9 2015-04-13]:  增ctc_define中曲轨分路不良定义MOPER_PARA_CBAD_SWITCH_C，增加ALARM_STPC_NO_PLAN\n"	\
"[V1.2.10 2015-11-30]: 增加MsgShuntRouteStatusReport(ID:210)\n" \
"[V1.2.11 2016-08-08]: 增加MsgTrainUpdate(const MsgTrainData& data)\n"  \
"[                  ]: MsgDataStyleReq2中DataStyle增加PREDICT\n"  \
"[                  ]: MAX_SCHD_BLOCK_ELE_COUNT由64扩大到512\n"  \
"[        2017-01-16]: 增加MsgTrainExpand等消息(ID:390-395)\n"  \
"[                  ]: MsgAlarmExd初始化函数改正错误，序列化函数优化\n"  \
"[                  ]: MsgHugeDataCtrl初始化函数增加内存清零\n"  \
"[                  ]: MsgAlarm::doSerialize由private改为protected\n"  \
"\n"
#endif //#ifndef  __MSGID_H__
