/* soapStub.h
   Generated by gSOAP 2.8.15 from ..\gsoap_input\MyWsSvr_ns2.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 20815
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_ns2__LoginResponse
#define SOAP_TYPE_ns2__LoginResponse (10)
/* ns2:LoginResponse */
struct ns2__LoginResponse
{
public:
	std::wstring result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
public:
	int soap_type() const { return 10; } /* = unique id SOAP_TYPE_ns2__LoginResponse */
};
#endif

#ifndef SOAP_TYPE_ns2__Login
#define SOAP_TYPE_ns2__Login (11)
/* ns2:Login */
struct ns2__Login
{
public:
	std::wstring szPara;	/* required element of type xsd:string */
public:
	int soap_type() const { return 11; } /* = unique id SOAP_TYPE_ns2__Login */
};
#endif

#ifndef SOAP_TYPE_ns2__QueryDataResponse
#define SOAP_TYPE_ns2__QueryDataResponse (13)
/* ns2:QueryDataResponse */
struct ns2__QueryDataResponse
{
public:
	std::wstring result_info;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
public:
	int soap_type() const { return 13; } /* = unique id SOAP_TYPE_ns2__QueryDataResponse */
};
#endif

#ifndef SOAP_TYPE_ns2__QueryData
#define SOAP_TYPE_ns2__QueryData (14)
/* ns2:QueryData */
struct ns2__QueryData
{
public:
	std::wstring szPara;	/* required element of type xsd:string */
public:
	int soap_type() const { return 14; } /* = unique id SOAP_TYPE_ns2__QueryData */
};
#endif

#ifndef SOAP_TYPE_ns2__UpdateDataResponse
#define SOAP_TYPE_ns2__UpdateDataResponse (16)
/* ns2:UpdateDataResponse */
struct ns2__UpdateDataResponse
{
public:
	std::wstring result_info;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
public:
	int soap_type() const { return 16; } /* = unique id SOAP_TYPE_ns2__UpdateDataResponse */
};
#endif

#ifndef SOAP_TYPE_ns2__UpdateData
#define SOAP_TYPE_ns2__UpdateData (17)
/* ns2:UpdateData */
struct ns2__UpdateData
{
public:
	std::wstring szPara;	/* required element of type xsd:string */
public:
	int soap_type() const { return 17; } /* = unique id SOAP_TYPE_ns2__UpdateData */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (18)
/* SOAP Header: */
struct SOAP_ENV__Header
{
public:
	int soap_type() const { return 18; } /* = unique id SOAP_TYPE_SOAP_ENV__Header */
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (19)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
public:
	int soap_type() const { return 19; } /* = unique id SOAP_TYPE_SOAP_ENV__Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (21)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
public:
	int soap_type() const { return 21; } /* = unique id SOAP_TYPE_SOAP_ENV__Detail */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (24)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 24; } /* = unique id SOAP_TYPE_SOAP_ENV__Reason */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (25)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
public:
	int soap_type() const { return 25; } /* = unique id SOAP_TYPE_SOAP_ENV__Fault */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 ns2__Login(struct soap*, std::wstring szPara, std::wstring &result);

SOAP_FMAC5 int SOAP_FMAC6 ns2__QueryData(struct soap*, std::wstring szPara, std::wstring &result_info);

SOAP_FMAC5 int SOAP_FMAC6 ns2__UpdateData(struct soap*, std::wstring szPara, std::wstring &result_info);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__Login(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__QueryData(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__UpdateData(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__Login(struct soap *soap, const char *soap_endpoint, const char *soap_action, std::wstring szPara, std::wstring &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__QueryData(struct soap *soap, const char *soap_endpoint, const char *soap_action, std::wstring szPara, std::wstring &result_info);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__UpdateData(struct soap *soap, const char *soap_endpoint, const char *soap_action, std::wstring szPara, std::wstring &result_info);

#endif

/* End of soapStub.h */
