// MyCmdL.cpp: implementation of the CMyCmdL class.
//
//////////////////////////////////////////////////////////////////////
#include "stdafx.h"
#include "MyCmdL.h"

//////////////////////////////////////////////////////////////////////
// Construction/Destruction
//////////////////////////////////////////////////////////////////////

CMyCmdL::CMyCmdL()
{
	m_bAutoLogin=false;
	m_bIgnServer=false;
	m_db_mode=-1;
	m_server_entity_id=0;
	m_nLogLevel=-1;
	m_nLogTypeMask=0xFFFF;
	m_bQueryMode=false;
	m_bShowAlarm=true;
	m_bStplanAlarm=false;
	m_bCommSvrMode=false;
	m_bGSMRCommMode=true;
	m_nStartCMDIndex=1;
	m_nEndCMDIndex=100;
	m_bNewMMI=false;
}

CMyCmdL::~CMyCmdL()
{

}

void CMyCmdL::ParseParam( LPCTSTR lpszParam, BOOL bFlag, BOOL bLast )
{
	if(bFlag)
	{
		m_lastflag=lpszParam;
		if(!stricmp(lpszParam,"AUTOLOGIN"))
			m_bAutoLogin=true;
		else
			if(!strnicmp(lpszParam,"USERID:",7))
			{
				m_userid=lpszParam+7;
			}
		else
			if(!strnicmp(lpszParam,"PASSWORD:",9))
			{
				m_password=lpszParam+9;
			}
		else
			if(!strnicmp(lpszParam,"SHIFTID:",8))
			{
				m_shiftid=atoi(lpszParam+8);
			}
		else
			if(!strnicmp(lpszParam,"USERNAME:",9))
			{
				m_username=lpszParam+9;
			}
		else
			if(!strnicmp(lpszParam,"GPCNAME:",8))
			{
				m_gpcname=lpszParam+8;
			}
		else
			if(!strnicmp(lpszParam,"DATAPATH:",9))
			{
				m_datapath=lpszParam+9;
			}
		else
			if(!strnicmp(lpszParam,"COMMCFG:",8))
			{
				m_commcfgfile=lpszParam+8;
			}
		else
			if(!strnicmp(lpszParam,"ENTITYCFG:",10))  
			{
				m_entityfile=lpszParam+10;
			}
		else
			if(!strnicmp(lpszParam,"SVRID:",6))
			{
				m_server_entity_id=atoi(lpszParam+6);
			}
		else
			if(!strnicmp(lpszParam,"DBMODE:",7))
			{
				m_db_mode=atoi(lpszParam+7);
			}
		else
			if(!stricmp(lpszParam,"IGNSVR"))
				m_bIgnServer=true;
		else
			if(!strnicmp(lpszParam,"LOGLEVEL:",9))
			{
				m_nLogLevel=atoi(lpszParam+9);
			}
		else
			if(!strnicmp(lpszParam,"LOGTYPE:",8))
			{
				m_nLogTypeMask=atoi(lpszParam+8);
			}
		else
		if(!stricmp(lpszParam,"QUERY"))
				m_bQueryMode=true;
		else
		if(!stricmp(lpszParam,"NOALARM"))
				m_bShowAlarm=false;
		else
		if(!stricmp(lpszParam,"NEWMMI"))
				m_bNewMMI=true;
		else
		if(!stricmp(lpszParam,"STPLANALARM"))
				m_bStplanAlarm=true;
		else
		if(!stricmp(lpszParam,"COMMSVR"))
				m_bCommSvrMode=true;
		else
		if(!strnicmp(lpszParam,"TGCFG:",6))
			{
				m_tgcfgfile=lpszParam+6;
			}
		else
		if(!strnicmp(lpszParam,"INITOPEN:",9))
			{
				m_nInitOpenWindow=atoi(lpszParam+9);
			}
		else
		if(!stricmp(lpszParam,"NOGSMR"))
				m_bGSMRCommMode=false;
		else
		if(!strnicmp(lpszParam,"STCMD:",6))
			{
				m_nStartCMDIndex=atoi(lpszParam+6);
			}
		else
		if(!strnicmp(lpszParam,"EDCMD:",6))
			{
				m_nEndCMDIndex=atoi(lpszParam+6);
			}
	}
	else
	{
		if(!m_lastflag.CompareNoCase("datapath"))
			m_datapath=lpszParam;
	}
}


